repos:
  - repo: local
    hooks:
      - id: mypy
        name: Type checking
        entry: just mypy
        language: system
        always_run: true
        pass_filenames: false
      - id: check
        name: Formatting and linting
        entry: just check
        language: system
        always_run: true
        pass_filenames: false
