repos:
  - repo: local
    hooks:
      - id: run-just-test
        name: All tests and checks
        entry: just test
        language: system
        always_run: true
        pass_filenames: false
