repos:
  - repo: local
    hooks:
      - id: mypy
        name: Type checking
        entry: just mypy
        language: system
        always_run: true
        pass_filenames: false
      - id: lint
        name: Linting and checking
        entry: just lint
        language: system
        always_run: true
        pass_filenames: false
