name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: citizensadvice/python-poetry-setup-action@v1

      - name: Install dependencies
        run: just install

      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest
        run: just pytest

  ruff:
    name: Ruff and MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: citizensadvice/python-poetry-setup-action@v1

      - name: Install dependencies
        run: just install

      - name: Run ruff checks
        run: just check

      - name: Run mypy checks
        run: just mypy