name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest
    # This does not work because you can't pass
    # commands into the container to start the
    # server! Massive limitation in Actions.
    # services:
    #   ntfy:
    #     image: binwiederhier/ntfy
    #     ports:
    #       - 80:80
    #     env:
    #       NTFY_ATTACHMENT_CACHE_DIR: /cache
    #       NTFY_BASE_URL: http://localhost
    steps:
      - uses: actions/checkout@v4

      - uses: citizensadvice/python-poetry-setup-action@v1

      - name: Install dependencies
        run: poetry install --with dev
      
      - name: Start test containers
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: tests/assets/test_containers.yml

      - name: Run pytest
        run: poetry run pytest -v --cov --cov-fail-under=95

  ruff:
    name: Ruff and MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: citizensadvice/python-poetry-setup-action@v1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run ruff format check
        run: poetry run ruff format --check

      - name: Run ruff check
        run: poetry run ruff check

      - name: Run MyPy
        run: poetry run mypy .

